notifications:
  slack: $slack
sudo: required
language: node_js
node_js:
    - "9.7.1"
install:
  - npm i
script:
  - npx ng lint
  - npx ng test @angeeks/gmaps --watch=false
  - npx ng build @angeeks/gmaps --prod
  - npx ng test gmaps --watch=false
  - npx ng build gmaps --prod --base-href gmaps
cache:
    directories:
      - node_modules
deploy:
  - provider: pages
    local-dir: dist/gmaps
    github-token: $github
    skip-cleanup: true
    keep-history: true
